### PR TITLE
django-admin startproject

### PR DESCRIPTION
**Pull request by ahmalla**
adding files for django startup, database not connected yet. we should all name our postgresql database "projectfour"

### CODE REVIEW

**Comment by dunndealpro** [comment]
Looks good

**Review by dunndealpro — COMMENTED** [review]
looks good

**Review by dunndealpro — APPROVED** [review]
looks

**Comment by jhubbell89** [comment]
good job

**Comment by jhubbell89** [comment]
hopefully this works

**Comment by jhubbell89** [comment]
hgfds

**Comment by jhubbell89** [comment]
jhgfdsdfg

**Review by jhubbell89 — APPROVED** [review]

**Pull request merged**
